services:
  database:
    container_name: db-manejo
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: app-manejo
    image: app-manejo
    entrypoint: ./entrypoint.sh
    build: .
    volumes:
      - app:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

volumes:
  pgdata:
  app: