services:
  database:
    container_name: db-manejo
    image: postgres:17-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: app-manejo
    image: manejo
    build: .
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
  
  adminer:
    container_name: adminer-manejo
    image: adminer
    depends_on:
      - database
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - "8080:8080"

volumes:
  pgdata: