services:
  database:
      restart: "no"

  app:
    restart: "no"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    # Ref: https://docs.docker.com/reference/compose-file/develop/
    develop:
      watch:
        - path: ./app
          action: sync
          target: /code/app
          ignore:
            - .venv
        - path: ./requirements.txt
          action: rebuild
  
  web:
    restart: "no"
  
  adminer:
    restart: "no"
  
  loki:
    restart: "no"
  
  prometheus:
    restart: "no"
  
  tempo:
    restart: "no"
  
  grafana:
    restart: "no"