services:
  psql:
    image: postgres:latest
    container_name: animals-psql
    environment:
      - POSTGRES_DB=db-manejo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data
volumes:
  db:
