services:
  postgres:
    image: postgres:latest
    container_name: animals-psql
    environment:
      - POSTGRES_DB=db-manejo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgresql
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: db-manejo
      DB_SSL: disable
volumes:
  db:
