services:
  database:
    container_name: db-manejo
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: app-manejo
    image: 'manejo:${TAG-latest}'
    restart: always
    build: .
    volumes:
      - ./app:/code/app
    depends_on:
      database:
        condition: service_healthy
        restart: true
    env_file:
      - .env
  
  web:
    container_name: web-manejo
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - app

  
  adminer:
    container_name: adminer-manejo
    image: adminer
    restart: always
    depends_on:
      - database
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    ports:
      - "8080:8080"

volumes:
  pgdata: