[tool.poetry]
name = "modernizacao-manejo-api"
version = "0.1.0"
description = ""
authors = ["Henrique Sebastião <henriquesebastiao.web@gmail.com>"]
readme = "README.md"
packages = [{include = "modernizacao_manejo_api"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.98.0"}
uvicorn = "^0.22.0"
sqlalchemy = "^2.0.15"
pydantic = {extras = ["dotenv", "email"], version = "^1.10.9"}
alembic = "^1.11.1"
asyncpg = "^0.27.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}

# Ferramentas de desenvolvimento
[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
taskipy = "^1.12.0"
blue = "^0.9.1"
ruff = "^0.0.285"
httpx = "^0.24.1"
isort = "^5.12.0"

## Início das configurações de desenvolvimento ##
[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79

[tool.pytest.ini_options]
pythonpath = "."

[tool.blue]
extend-exclude = '(migrations/)'

# Tasks
[tool.taskipy.tasks]
lint = 'ruff . && blue --check . --diff'
format = 'blue .  && isort .'
run = 'uvicorn app.main:app --reload'
pre_test = 'task lint'
test = 'pytest -s -x --cov=app -vv'
post_test = 'coverage html'
## Fim das configurações de desenvolvimento ##

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
