[tool.poetry]
name = "modernizacao-manejo-api"
version = "0.1.0"
description = ""
authors = ["Henrique Sebastião <henriquesebastiao.web@gmail.com>"]
readme = "README.md"
packages = [{include = "modernizacao_manejo_api"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.2"
uvicorn = "^0.22.0"
sqlalchemy = "^2.0.15"
psycopg2 = "^2.9.6"
pydantic = "^1.10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
