[tool.poetry]
name = "modernizacao-manejo-api"
version = "0.1.0"
description = ""
authors = ["Henrique Sebastião <henriquesebastiao.web@gmail.com>"]
readme = "README.md"
packages = [{include = "modernizacao_manejo_api"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.98.0"}
uvicorn = "^0.22.0"
sqlalchemy = "^2.0.15"
pydantic = {extras = ["dotenv", "email"], version = "^1.10.9"}
alembic = "^1.11.1"
asyncpg = "^0.27.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
