"""inicio

Revision ID: 1238dab14c5f
Revises: 
Create Date: 2023-06-07 02:56:55.799372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1238dab14c5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propriedade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('fazendeiro_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chip', sa.String(), nullable=True),
    sa.Column('brinco', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('raca_id', sa.Integer(), nullable=True),
    sa.Column('id_mae', sa.Integer(), nullable=True),
    sa.Column('id_pai', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['raca_id'], ['raca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobre_nome', sa.String(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peso_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fazendeiro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fazenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fazendeiro_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fazendeiro_id'], ['fazendeiro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fazenda')
    op.drop_table('fazendeiro')
    op.drop_table('usuario')
    op.drop_table('peso_log')
    op.drop_table('lote_log')
    op.drop_table('pessoa')
    op.drop_table('animal')
    op.drop_table('raca')
    op.drop_table('propriedade')
    op.drop_table('lote')
    op.drop_table('cargo')
    # ### end Alembic commands ###
