"""remove animal weight type table

Revision ID: 520a94e94127
Revises: 436c61f7e398
Create Date: 2024-11-14 09:38:25.848852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520a94e94127'
down_revision: Union[str, None] = '436c61f7e398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_weight_type')
    op.add_column('animal_weight', sa.Column('weight_type', sa.String(), nullable=False))
    op.drop_column('animal_weight', 'weight_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_weight', sa.Column('weight_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('animal_weight', 'weight_type')
    op.create_table('animal_weight_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='animal_weight_type_pkey')
    )
    # ### end Alembic commands ###
