"""rename animal_id column for animal_tag in animal weight table

Revision ID: 5d3b7526155e
Revises: 520a94e94127
Create Date: 2024-11-14 09:42:20.355331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3b7526155e'
down_revision: Union[str, None] = '520a94e94127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_weight', sa.Column('animal_tag', sa.Integer(), nullable=False))
    op.drop_column('animal_weight', 'animal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_weight', sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('animal_weight', 'animal_tag')
    # ### end Alembic commands ###
