"""populate

Revision ID: 97a3fa496a69
Revises: 2f21bb73462a
Create Date: 2023-06-22 12:47:53.692413

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '97a3fa496a69'
down_revision = '2f21bb73462a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    animal_weight_type = sa.sql.table("animal_weight_type",
                                      sa.sql.column("id", sa.Integer),
                                      sa.sql.column("name", sa.String))

    op.bulk_insert(animal_weight_type, [
        {"id": 1, "name": "nascimento"},
        {"id": 2, "name": "entrada"},
        {"id": 3, "name": "desmama"},
        {"id": 4, "name": "saída"},
        {"id": 5, "name": "manejo"},
    ])

    employment_position = sa.sql.table("employment_position",
                                       sa.sql.column("id", sa.Integer),
                                       sa.sql.column("name", sa.String))

    op.bulk_insert(employment_position, [
        {"id": 1, "name": "Avaliação"},
        {"id": 2, "name": "Pequeno produtor"},
        {"id": 3, "name": "Medio produtor"},
        {"id": 4, "name": "Grande produtor"},
        {"id": 5, "name": "Personalizado"},
    ])

    breed = sa.sql.table("breed",
                         sa.sql.column("id", sa.Integer),
                         sa.sql.column("name", sa.String))

    op.bulk_insert(breed, [
        {"id": 1, "name": "Nelore"},
        {"id": 2, "name": "Angus"},
        {"id": 3, "name": "Brahman"},
    ])

    farmer_plan = sa.sql.table("farmer_plan", sa.sql.column("id", sa.Integer),
                               sa.sql.column("plan", sa.String))

    op.bulk_insert(farmer_plan, [
        {"id": 1, "plan": "Avaliação"},
        {"id": 2, "plan": "Pequeno produtor"},
        {"id": 3, "plan": "Medio produtor"},
        {"id": 4, "plan": "Grande produtor"},
        {"id": 5, "plan": "Personalizado"},
    ])

    user_type = sa.sql.table("user_type", sa.sql.column("id", sa.Integer),
                             sa.sql.column("type", sa.String))

    op.bulk_insert(user_type, [
        {"id": 1, "type": "Administrador"},
        {"id": 2, "type": "Fazendeiro"},
        {"id": 3, "type": "Funcionário"},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM user_type WHERE id IN (1, 2, 3)")
    op.execute("DELETE FROM farmer_plan WHERE id IN (1, 2, 3, 4, 5)")
    op.execute("DELETE FROM employment_position WHERE id IN (1, 2, 3, 4, 5)")
    op.execute("DELETE FROM animal_weight_type WHERE id IN (1, 2, 3, 4, 5)")
    # ### end Alembic commands ###
