"""updating origin column in animal table

Revision ID: a86e37fb3f31
Revises: 0a7dbc3b7e05
Create Date: 2024-11-06 13:36:46.426773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86e37fb3f31'
down_revision: Union[str, None] = '0a7dbc3b7e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('origin', sa.String(), nullable=False))
    op.drop_column('animal', 'origin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('animal', 'origin')
    # ### end Alembic commands ###
