"""criando_tabela_dieta

Revision ID: f101ee2246e1
Revises: a0c243e6daae
Create Date: 2023-06-08 19:59:35.597382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f101ee2246e1'
down_revision = 'a0c243e6daae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dieta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lote', sa.Column('dieta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lote', 'dieta', ['dieta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lote', type_='foreignkey')
    op.drop_column('lote', 'dieta_id')
    op.drop_table('dieta')
    # ### end Alembic commands ###
