"""pessoa_nascimento

Revision ID: fbfd732f9aff
Revises: fdb4dd920e7a
Create Date: 2023-06-07 02:59:15.244511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfd732f9aff'
down_revision = 'fdb4dd920e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoa', sa.Column('data_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoa', 'data_nascimento')
    # ### end Alembic commands ###
