on: [push, pull_request]

name: Test

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      UV_SYSTEM_PYTHON: 1
      APP_BIND_HOST: 0.0.0.0
      PYTHON_COLORS: 0

    steps:
      - name: Copy files from repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Run Ruff
        run: uv run ruff check .; uv run ruff check . --diff
      
      - name: Run Radon
        run: uv run radon cc ./app -a -na
      
      - name: Run Bandit
        run: uv run bandit -r ./app

      - name: Run Tests
        run: uv run task test

      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov